# Generated by Django 4.2.2 on 2023-06-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_categery_product_catagery_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
